/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiGoogleConnectRouteImport } from './routes/api/google/connect'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleConnectRoute = ApiGoogleConnectRouteImport.update({
  id: '/api/google/connect',
  path: '/api/google/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/signin': typeof SigninRoute
  '/courses': typeof AppCoursesRoute
  '/history': typeof AppHistoryRoute
  '/journal': typeof AppJournalRoute
  '/settings': typeof AppSettingsRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/courses': typeof AppCoursesRoute
  '/history': typeof AppHistoryRoute
  '/journal': typeof AppJournalRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/courses'
    | '/history'
    | '/journal'
    | '/settings'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/google/callback'
    | '/api/google/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/courses'
    | '/history'
    | '/journal'
    | '/settings'
    | '/'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/google/callback'
    | '/api/google/connect'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/courses'
    | '/_app/history'
    | '/_app/journal'
    | '/_app/settings'
    | '/_app/'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/google/callback'
    | '/api/google/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleConnectRoute: typeof ApiGoogleConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/connect': {
      id: '/api/google/connect'
      path: '/api/google/connect'
      fullPath: '/api/google/connect'
      preLoaderRoute: typeof ApiGoogleConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCoursesRoute: typeof AppCoursesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppJournalRoute: typeof AppJournalRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoursesRoute: AppCoursesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppJournalRoute: AppJournalRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleConnectRoute: ApiGoogleConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
